export enum DefaultStyles {
    PRIMARY_COLOR = "#EEE",
    SECONDARY_COLOR = "#727272",
    TERTIARY_COLOR = "#555",
    BACKGROUND_COLOR = "#2B2B2B",
    CARD_COLOR = "#363E40",
    ANCHOR_COLOR = "#30A7C1",
    PLACEHOLDER_COLOR = "#363E40",
    BUTTON_COLOR = "#EEE",
    BUTTON_TEXT_COLOR = "#000",
    DISABLED_COLOR = "#727272",
    ERROR_COLOR = "#F86262",
    ERROR_COLOR_LIGHT = "#F1CBCB",
    SUCCESS_COLOR = "#5CB85C",
    ICON_COLOR = "white"
}
